development: &default
  adapter: mysql2
  encoding: utf8
  database: onlynet_dev
  host: localhost
  username: onlynet
  password: '#EDC4rfv'

test: &TEST
  <<: *default
  database: onlynet_test

production: &PROD
  <<: *default
  database: onlynet_prod